server:
  port: 8761
eureka:
  client:
    # cancel eureka self-registry
    register-with-eureka: false
    fetch-registry: false

    # service registry url
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/